apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: healthcheckapp
  name: healthcheckapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcheckapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: healthcheckapp
    spec:
      containers:
      - image: gcr.io/pdcgcloudtest/healthcheckapp:latest
        name: healthcheckapp
        resources: {}
status: {}
